# Stage 2: Frontend
FROM node:alpine AS frontend

WORKDIR /app

# Copy the package.json and package-lock.json to /app
COPY ../frontend/package.json ./package.json
COPY ../frontend/package-lock.json ./package-lock.json

# Install dependencies
RUN npm install -g @angular/cli
RUN npm install

# Copy the rest of the frontend files
COPY ../frontend /app

RUN ng add @angular/material

CMD ["ng", "serve", "--host", "0.0.0.0"]
