version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile_backend
    ports:
      - "8000:8000"
#  frontend:
#    build:
#      context: .
#      dockerfile: frontend/Dockerfile_frontend
#    ports:
#      - "4200:4200"