FROM python:3.10

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY ./src/db.json /app/db.json
COPY ./src /app

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
